name: ci

env:
  CTEST_PARALLLEL_LEVEL: 3
  CMAKE_BUILD_TYPE: Release
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"


jobs:

  fortran:
    strategy:
      matrix:
        shared: [true, false]
        img: [ {os: ubuntu-latest, fc: gfortran, cmake_gen: Unix Makefiles},
               {os: macos-latest, fc: gfortran-11, cmake_gen: Unix Makefiles},
               {os: windows-latest, fc: gfortran, cmake_gen: MinGW Makefiles}
        ]

    runs-on: ${{ matrix.img.os }}
    timeout-minutes: 7
    env:
      FC: ${{ matrix.img.fc }}
      CMAKE_GENERATOR: ${{ matrix.img.cmake_gen }}

    steps:

    - uses: actions/checkout@v2

    - name: config shared=${{ matrix.shared }}
      run: cmake -B build -Darith=d -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: build
      run: cmake --build build --parallel

    - name: test
      run: ctest --test-dir build --preset default -V
