name: ci

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLLEL_LEVEL: 3
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset default -Darith=d
    - run: cmake --build --preset default
    - run: ctest --preset default


  windows:
    needs: linux
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset default -Darith=d -G "MinGW Makefiles"
    - run: cmake --build --preset default
    - run: ctest --preset default


  mac:
    needs: linux
    runs-on: macos-latest
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset default -Darith=d
    - run: cmake --build --preset default
    - run: ctest --preset default
