name: ci

env:
  CMAKE_BUILD_TYPE: Release
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"


jobs:

  fortran:
    strategy:
      matrix:
        shared: [true, false]
        img: [ {os: ubuntu-latest, cmake_gen: Unix Makefiles},
               {os: macos-latest, cmake_gen: Unix Makefiles},
               {os: windows-latest, cmake_gen: MinGW Makefiles}
        ]

    runs-on: ${{ matrix.img.os }}
    timeout-minutes: 7
    env:
      CMAKE_GENERATOR: ${{ matrix.img.cmake_gen }}

    steps:

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.19'

    - name: install Gfortran
      if: runner.os == 'macOS'
      run: brew reinstall gcc

    - uses: actions/checkout@v3

    - name: config shared=${{ matrix.shared }}
      run: cmake -B build -Darith=d -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }}

    - name: build
      run: cmake --build build --parallel

    - name: test
      run: ctest --test-dir build --preset default -V

    - name: install
      run: cmake --install build

    - name: example config
      run: cmake -S example -B example/build -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }}

    - name: example build
      run: cmake --build example/build

    - name: example test
      run: ctest --test-dir example/build
