name: ci_macos
env:
   HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - "**./meson.build"
      - ".github/workflows/ci_macos.yml"


jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset=makemac -Darith=d
    - run: cmake --build build --parallel
    - run: ctest --parallel 2 --output-on-failure
      working-directory: build


  meson:
    if: false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build -Darith=d
      env:
        FC: gfortran-10

    - run: meson compile -C build
    - run: meson test -C build -v
