name: ci_windows

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - "**/meson.build"
      - ".github/workflows/ci_windows.yml"


jobs:

  cmake:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset=makewin -Darith=d
    - run: cmake --build build --parallel
    - run: ctest --parallel 2 --output-on-failure
      working-directory: build

  meson:
    if: false
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build -Darith=d
    - run: meson compile -C build
    - run: meson test -C build -v
